# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e89705783986fcad4bf23b95f1d21e585a96696eb6d3be838bb0171adffa90630621fed69ccb2c2ae2c93e902ebd2d040d86ab8ff7c182faf5e5eead82175d5

test:
  secret_key_base: 15adb58589ea39e7125361f2987aeb8f0c22a5837d6f639978cb2c313505a8695381fb7567c257d3cef400e5c32816d1b2fb59fdeeaa7a34e6863ceeb808b461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
